spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: password
        url: jdbc:mysql://localhost:3308/xdkt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapper-locations: classpath*:mybatis/**/*Mapper.xml
    # 搜索指定包别名
    type-aliases-package: com.status.domain
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

#showSql
logging:
    level:
        com:
            example:
                mapper : debug